import AppError from "../errors/AppError";

export default class AcusadoNotFoundException extends AppError {
  constructor() {
    super("Acusado n√£o encontrado.", 404);
  }
}
